### ISSUE TITLE
fix typo in block name

### ISSUE THREAD

**Issue by sameoldmadness** [remnev/stat-counters#17]
metrica -> metrika

**Comment by remnev** [comment]
https://github.com/remnev/stat-counters/pull/8#discussion_r28146552

**Comment by sameoldmadness** [comment]
Я бы посчитал, что важнее поддержать единообразие с конструктором, а он всё-таки `Ya.Metrika`.

**Comment by sameoldmadness** [comment]
В примере из ридми используется оба написания радом — выглядит странно.

**Comment by zxqfox** [comment]
Мде... Надо как-то определится уже с этим и добавить в git postcommit проверку на наличие metrika. :fire:

**Comment by remnev** [comment]
Надо спросить у самой метрики, что они думают об этом. Я отпишусь по результатам.

**Comment by sameoldmadness** [comment]
Ещё можно погрепать репозитории, которые уже используют метрику.

**Comment by zxqfox** [comment]
:+1:

**Comment by remnev** [comment]
Команда метрики сказала, что для en правильное название metrica. Я хочу, чтобы нерусскоговорящим людям было проще работать с блоком, поэтому с текущим названием блока все ок.

А документацию надо поправить — #30.
